import type { Metadata } from 'next'
import Link from 'next/link'
import { FlaskConical, Building2, BarChart3, CheckCircle2 } from 'lucide-react'
import CTABanner from '@/components/cta-banner'
import SchemaOrg from '@/components/schema-org'
import HeroSection from '@/components/home/hero-section'
import BlogPreview from '@/components/home/blog-preview'
import { SredCalculator } from '@/components/sred-calculator'
import { TestimonialsCarousel } from '@/components/testimonials-carousel'

export const metadata: Metadata = {
  title: 'SR&ED Tax Credits & Government Funding | Wavecrest Strategies | Canada',
  description: 'Wavecrest Strategies helps Canadian founders maximize SR&ED tax credits and government funding. Founder-built. Big 4 pedigree. Transparent fees. Free audit defense.',
  openGraph: {
    title: 'SR&ED Tax Credits & Government Funding | Wavecrest Strategies',
    description: 'Builder-friendly SR&ED consulting for Canadian startups. Transparent fees, free audit defense, and a team that has ridden the same waves.',
    url: 'https://www.wavecreststrategies.ca',
    siteName: 'Wavecrest Strategies',
    locale: 'en_CA',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SR&ED Tax Credits & Government Funding | Wavecrest Strategies',
    description: 'Builder-friendly SR&ED consulting for Canadian startups.',
  },
  alternates: { canonical: 'https://www.wavecreststrategies.ca' },
}

const homeSchema = {
  '@context': 'https://schema.org',
  '@type': 'ProfessionalService',
  name: 'Wavecrest Strategies',
  url: 'https://www.wavecreststrategies.ca',
  description: 'Canadian SR&ED tax credit consulting and government funding strategy firm. Builder-friendly, founder-built, Big 4 pedigree.',
  areaServed: 'CA',
  serviceType: ['SR&ED Tax Credits', 'Government Funding Strategy', 'Fractional Financial Services'],
  founder: { '@type': 'Person', name: 'Marc Hanna' },
  sameAs: ['https://www.linkedin.com/company/wavecrest-strategies'],
}

const services = [
  {
    icon: FlaskConical,
    title: 'SR&ED Tax Credits',
    body: "We handle every aspect of your SR&ED claim - technical narrative, financial calculations, CRA submission, and audit defense if needed. Our team has Big 4 depth with boutique attention. Typical clients recover 20-35% of qualifying R&D expenditures.",
    href: '/services#sred',
  },
  {
    icon: Building2,
    title: 'Fundraising & Grant Strategy',
    body: "Canada's funding landscape is complex and constantly changing. We map every applicable federal and provincial program for your company - IRAP, NRC, regional funds, and sector-specific grants - and build a strategy to capture them.",
    href: '/services#funding',
  },
  {
    icon: BarChart3,
    title: 'Fractional Financial Services',
    body: "Get the financial clarity of a senior CFO or controller without the full-time cost. Bookkeeping, financial reporting, and strategic finance support on a fractional basis - built around your stage and budget.",
    href: '/services#fractional',
  },
]

const promises = [
  { title: 'Best Rate Guarantee', desc: 'If we can\'t beat your current provider\'s rate, we won\'t take your business. We benchmark against Big 4 firms and boutique consultants before we quote.' },
  { title: 'Work on Your Timeline, Not Ours', desc: 'Big firms schedule you in. We don\'t. When you need your claim done, we make it happen. Flexibility is part of the service, not an upgrade.' },
  { title: 'No Hidden Fees. Full Stop.', desc: 'No fees on CRA interest payments. No hidden administration charges. Our quote is all-in. What you see is what you pay. Full Transparency. No surprises.' },
  { title: 'Free Audit Defense, Always', desc: 'If CRA selects your claim for review, we manage the entire process at zero additional cost. We prepare the responses, attend the meetings, and defend your claim. No surprises, no invoices.' },
  { title: 'Human Expertise. No AI Slop.', desc: 'Qualified humans lead and oversee the preparation of every claim. Your technical narrative is written by experienced practitioners who understand CRA\'s expectations - not generated by an AI and sent out the door.' },
]

const industries = [
  { icon: '💻', label: 'Software & SaaS' },
  { icon: '🔬', label: 'Life Sciences & Biotech' },
  { icon: '⚡', label: 'Cleantech & Energy' },
  { icon: '🏭', label: 'Advanced Manufacturing' },
  { icon: '🚀', label: 'Aerospace & Defence' },
  { icon: '🤖', label: 'AI & Machine Learning' },
]

export default function HomePage() {
  return (
    <>
      <SchemaOrg schema={homeSchema} />

      {/* Section 1: Hero */}
      <HeroSection />

      {/* Section 2: Testimonials Carousel */}
      <TestimonialsCarousel />

      {/* Section 3: The Problem We Solve */}
      <section className="bg-white py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-[#2563eb] text-xs font-semibold uppercase tracking-widest mb-4">Built for Founders</p>
          <h2 className="font-serif text-3xl md:text-[40px] text-[#0f2744] font-bold mb-6 leading-tight text-balance">
            SR&amp;ED is money you&apos;ve already earned. We make sure you keep it.
          </h2>
          <p className="text-[#475569] text-lg leading-relaxed mb-4 max-w-3xl mx-auto">
            The SR&amp;ED program distributes over $3 billion to Canadian companies every year - but most founders never claim it. Those who do often overpay, spend months on prep, and get hit with surprise audit fees. We built Wavecrest to be the firm we wished existed when we were in your shoes.
          </p>
          <p className="text-[#475569] text-base leading-relaxed mb-12 max-w-2xl mx-auto font-medium">
            Founder-built. Founder-priced. Founder-friendly - every step of the way.
          </p>
        </div>
      </section>

      {/* Section 4: Services Overview */}
      <section className="bg-[#f8f7f4] py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[#2563eb] text-xs font-semibold uppercase tracking-widest mb-4">What We Do</p>
            <h2 className="font-serif text-3xl md:text-[40px] text-[#0f2744] font-bold text-balance">
              Three ways we help you grow.
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {services.map((service) => (
              <div
                key={service.title}
                className="bg-white border border-[#e2e8f0] rounded-xl p-8 hover:shadow-md transition-shadow"
              >
                <div className="w-12 h-12 rounded-full bg-[#f8f7f4] border border-[#e2e8f0] flex items-center justify-center mb-5">
                  <service.icon size={22} className="text-[#0f2744]" />
                </div>
                <h3 className="font-serif text-[#0f2744] text-2xl font-semibold mb-3">{service.title}</h3>
                <p className="text-[#475569] text-sm leading-relaxed mb-5">{service.body}</p>
                <Link
                  href={service.href}
                  className="text-[#2563eb] text-sm font-medium hover:underline"
                >
                  Learn more &rarr;
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Section 5: The Five Promises */}
      <section className="bg-[#0f2744] py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[#3b82f6] text-xs font-semibold uppercase tracking-widest mb-4">The Founder-Friendly Standard</p>
            <h2 className="font-serif text-3xl md:text-[40px] text-white font-bold text-balance">
              Five commitments every founder gets. In writing.
            </h2>
            <p className="text-[#94a3b8] text-base mt-4 max-w-xl mx-auto leading-relaxed">
              We designed these around one question: how would we want to be treated if we were still founders?
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {promises.map((promise, i) => (
              <div
                key={promise.title}
                className={`flex gap-4 ${i === 4 ? 'md:col-span-2 md:max-w-md md:mx-auto' : ''}`}
              >
                <CheckCircle2 size={22} className="text-[#16a34a] shrink-0 mt-0.5" />
                <div>
                  <p className="text-white font-semibold mb-1">{promise.title}</p>
                  <p className="text-[#94a3b8] text-sm leading-relaxed">{promise.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Section 6: SR&ED Calculator */}
      <SredCalculator />

      {/* Section 7: Who We Serve */}
      <section className="bg-[#f8f7f4] py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <p className="text-[#2563eb] text-xs font-semibold uppercase tracking-widest mb-4">Who We Serve</p>
            <h2 className="font-serif text-3xl md:text-[40px] text-[#0f2744] font-bold mb-5 text-balance">
              Founder-friendly by design. Proven across every sector.
            </h2>
            <p className="text-[#475569] text-lg leading-relaxed max-w-3xl mx-auto">
              We work with Canadian founders across every sector - software, hardware, biotech, cleantech, manufacturing, and more. If your team is solving hard technical problems, there is a strong chance you qualify for SR&amp;ED.
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-10">
            {industries.map((ind) => (
              <div
                key={ind.label}
                className="bg-white border border-[#e2e8f0] rounded-xl p-5 text-center hover:shadow-sm transition-shadow"
              >
                <span className="text-2xl block mb-2" role="img" aria-label={ind.label}>{ind.icon}</span>
                <span className="text-[#0f2744] text-sm font-medium">{ind.label}</span>
              </div>
            ))}
          </div>

          <p className="text-center text-[#475569] text-sm">
            Not sure if you qualify? Most founders are surprised.{' '}
            <Link href="/contact" className="text-[#2563eb] hover:underline font-medium">
              Take our free 5-minute eligibility check &rarr;
            </Link>
          </p>
        </div>
      </section>

      {/* Section 8: Blog Preview */}

      {/* Section 9: CTA Banner */}
      <CTABanner />
    </>
  )
}
